# Generated by Django 4.0.10 on 2023-05-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productbin_storage_receipt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbin_storagereceipt',
            old_name='prduct_bin',
            new_name='product_bin',
        ),
        migrations.AlterUniqueTogether(
            name='productbin_storagereceipt',
            unique_together={('product_bin', 'storage_receipt')},
        ),
    ]
